# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b50dc3a9634f62aa13923f1302ed39bc79e2ac7b172403144143cd446e6027af8544023db72706fb08d021341097dd26ae24cd3d60476daf09e4f441d6e810

test:
  secret_key_base: ecb8bacc16cde8f59a31bc6cba5e0a15d328a47898c5789b01f3a38576e09ef4da35538f2e936c04290004f0961724d237c9c16b7892fddb8e7e34ee42ada46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
